name: Metrics
on:
  # Update otomatis setiap jam 00:00
  schedule: [{cron: "0 0 * * *"}]
  # Bisa dijalankan manual
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token ini otomatis ada, tidak perlu buat baru
          token: ${{ secrets.GITHUB_TOKEN }}

          # Opsi: User
          user: kelfinofarelino
          template: classic
          base: ""
          config_timezone: Asia/Jakarta
          
          # Plugin: Kalender Streak (Isocalendar)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
