name: Calendar
on:
  # Update otomatis setiap jam 00:00
  schedule: [{cron: "0 0 * * *"}]
  # Bisa dijalankan manual
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token ini otomatis ada, tidak perlu buat baru
          token: ${{ secrets.GITHUB_TOKEN }}

          # Opsi: User
          user: kelfinofarelino
          template: classic
          base: ""
          config_timezone: Asia/Jakarta
          
          # Plugin: Kalender Streak (Isocalendar)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # --- BAGIAN INI UNTUK MENYAMAKAN WARNA ---
          # Background: #141321 (Gelap Keunguan)
          # Judul: #fe428e (Pink)
          # Teks: #a9fef7 (Cyan/Biru Muda)
          extras_css: |
            svg { background-color: #141321 !important; border-radius: 6px; }
            .header, h1, h2, h3 { fill: #fe428e !important; }
            text, .field, .stat { fill: #a9fef7 !important; }
