name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: kelfinofarelino
          template: classic
          base: ""
          config_timezone: Asia/Jakarta
          
          # Plugin: Kalender Streak
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # --- KONFIGURASI WARNA (TEMA RADICAL) ---
          # Mengubah warna agar sama persis dengan gambar yang kamu kirim
          extras_css: |
            /* Background Gelap Keunguan */
            svg { background-color: #141321 !important; border-radius: 6px; }
            
            /* Judul Besar (Pink) */
            .header, h1, h2, h3 { fill: #fe428e !important; }
            
            /* Teks Biasa & Label (Cyan/Biru Muda) */
            text, .field, .stat { fill: #a9fef7 !important; }
            
            /* Warna Ikon (Opsional: Kuning agar kontras) */
            .icon svg { fill: #f8d847 !important; }
